/**
 * Europe (Other) — curated seed data.
 * Covers: Spain (Rioja, Ribera del Duero, Priorat), Portugal (Douro Valley, Alentejo),
 *         Germany (Mosel, Rheingau), Austria
 */

export const producers = [
  // SPAIN — RIOJA
  {
    id: "prod-lopez-de-heredia",
    name: "López de Heredia",
    country: "Spain",
    region: "Rioja",
    website: "https://www.lopezdeheredia.com",
    foundedYear: 1877,
    description: "Time stands still at this Haro bodega where wines age for decades in barrel, unchanged since 1877 — the soul of traditional Rioja.",
  },
  {
    id: "prod-la-rioja-alta",
    name: "La Rioja Alta",
    country: "Spain",
    region: "Rioja",
    website: "https://www.riojalta.com",
    foundedYear: 1890,
    description: "One of Rioja's most respected bodegas, renowned for classic, long-aged reservas and gran reservas from Rioja Alta vineyards.",
  },
  // SPAIN — RIBERA DEL DUERO
  {
    id: "prod-vega-sicilia",
    name: "Vega Sicilia",
    country: "Spain",
    region: "Ribera del Duero",
    website: "https://www.vega-sicilia.com",
    foundedYear: 1864,
    description: "Spain's most iconic winery, producing Único — a Tempranillo masterpiece aged for a decade that rivals the world's greatest reds.",
  },
  // SPAIN — PRIORAT
  {
    id: "prod-alvaro-palacios",
    name: "Álvaro Palacios",
    country: "Spain",
    region: "Priorat",
    website: "https://www.alvaropalacios.com",
    foundedYear: 1989,
    description: "The visionary who revived Priorat, creating L'Ermita — Spain's most expensive wine — from ancient Garnacha vines on steep llicorella slate.",
  },
  // PORTUGAL — DOURO
  {
    id: "prod-quinta-do-noval",
    name: "Quinta do Noval",
    country: "Portugal",
    region: "Douro Valley",
    website: "https://www.quintadonoval.com",
    foundedYear: 1715,
    description: "Home of Nacional, the world's rarest Vintage Port from ungrafted pre-phylloxera vines, and increasingly acclaimed dry Douro reds.",
  },
  {
    id: "prod-niepoort",
    name: "Niepoort",
    country: "Portugal",
    region: "Douro Valley",
    website: "https://www.niepoort-vinhos.com",
    foundedYear: 1842,
    description: "Fifth-generation family Port house that helped pioneer the Douro's transformation into one of Europe's most exciting dry wine regions.",
  },
  // PORTUGAL — ALENTEJO
  {
    id: "prod-herdade-do-esporao",
    name: "Herdade do Esporão",
    country: "Portugal",
    region: "Alentejo",
    website: "https://www.esporao.com",
    foundedYear: 1267,
    description: "Vast Alentejo estate blending ancient heritage with modern sustainability, producing Portugal's most recognized wines internationally.",
  },
  // GERMANY — MOSEL
  {
    id: "prod-egon-muller",
    name: "Egon Müller",
    country: "Germany",
    region: "Mosel",
    website: null,
    foundedYear: 1797,
    description: "Producer of the world's most expensive white wine — Scharzhofberger Trockenbeerenauslese — from the steep slate slopes above the Saar.",
  },
  {
    id: "prod-jj-prum",
    name: "Joh. Jos. Prüm",
    country: "Germany",
    region: "Mosel",
    website: "https://www.jjprum.com",
    foundedYear: 1911,
    description: "The quintessential Mosel estate, producing crystalline Rieslings from the famed Wehlener Sonnenuhr vineyard with legendary aging potential.",
  },
  // GERMANY — RHEINGAU
  {
    id: "prod-robert-weil",
    name: "Robert Weil",
    country: "Germany",
    region: "Rheingau",
    website: "https://www.weingut-robert-weil.com",
    foundedYear: 1875,
    description: "Rheingau's premier estate, producing aristocratic Rieslings from the Kiedrich Gräfenberg vineyard — from bone-dry to nobly sweet.",
  },
  // AUSTRIA (not a mapped region — will use closest or skip map pin)
  {
    id: "prod-fx-pichler",
    name: "F.X. Pichler",
    country: "Austria",
    region: "Wachau",
    website: "https://www.fx-pichler.at",
    foundedYear: 1898,
    description: "Austria's most celebrated winery, producing monumentally powerful dry Rieslings and Grüner Veltliners from Wachau's steep terraces.",
  },
];

export const wines = [
  // RIOJA
  {
    id: "wine-lopez-de-heredia-vina-tondonia-reserva-2011",
    name: "López de Heredia Viña Tondonia Reserva 2011",
    producer: "López de Heredia",
    producerId: "prod-lopez-de-heredia",
    vintage: 2011,
    grapes: ["Tempranillo", "Garnacha", "Graciano", "Mazuelo"],
    region: "Rioja",
    country: "Spain",
    appellation: "Rioja DOCa",
    type: "red",
    priceRange: "premium",
    description: "Six years in barrel and three in bottle before release — this is traditional Rioja at its most authentic and profound.",
    tastingNotes: "Dried cherry, leather, tobacco, balsamic, and sweet cedar. Ethereal tannins with haunting complexity and a seemingly endless finish.",
    foodPairing: "Roast suckling pig, slow-braised lamb, Manchego cheese, chorizo and white bean stew.",
  },
  {
    id: "wine-la-rioja-alta-gran-reserva-904-2015",
    name: "La Rioja Alta Gran Reserva 904 2015",
    producer: "La Rioja Alta",
    producerId: "prod-la-rioja-alta",
    vintage: 2015,
    grapes: ["Tempranillo", "Graciano"],
    region: "Rioja",
    country: "Spain",
    appellation: "Rioja DOCa",
    type: "red",
    priceRange: "premium",
    description: "Iconic gran reserva aged four years in American oak, blending the warmth of Rioja tradition with remarkable freshness.",
    tastingNotes: "Ripe strawberry, coconut, vanilla, leather, and dried herbs. Silky texture with balanced acidity and a warm, spicy finish.",
    foodPairing: "Roast lamb with pimentón, grilled pork tenderloin, Idiazábal cheese, patatas a la riojana.",
  },
  // RIBERA DEL DUERO
  {
    id: "wine-vega-sicilia-unico-2013",
    name: "Vega Sicilia Único 2013",
    producer: "Vega Sicilia",
    producerId: "prod-vega-sicilia",
    vintage: 2013,
    grapes: ["Tempranillo", "Cabernet Sauvignon"],
    region: "Ribera del Duero",
    country: "Spain",
    appellation: "Ribera del Duero DO",
    type: "red",
    priceRange: "luxury",
    description: "Spain's most legendary wine, aged for a decade in a combination of French and American oak before release. Only made in great vintages.",
    tastingNotes: "Dark plum, leather, sweet spice, cedarwood, and dried violets. Immensely complex with fine-grained tannins and extraordinary depth.",
    foodPairing: "Roast suckling lamb, grilled Ibérico pork, aged Manchego 36 months, braised oxtail.",
  },
  // PRIORAT
  {
    id: "wine-alvaro-palacios-les-terrasses-2021",
    name: "Álvaro Palacios Les Terrasses 2021",
    producer: "Álvaro Palacios",
    producerId: "prod-alvaro-palacios",
    vintage: 2021,
    grapes: ["Garnacha", "Cariñena", "Cabernet Sauvignon"],
    region: "Priorat",
    country: "Spain",
    appellation: "Priorat DOCa",
    type: "red",
    priceRange: "mid",
    description: "The gateway to Priorat's terraced slate vineyards, blending old-vine Garnacha with Cariñena for a mineral, Mediterranean red.",
    tastingNotes: "Ripe blackberry, slate, garrigue herbs, licorice, and smoked meat. Medium-full body with chalky tannins and a mineral finish.",
    foodPairing: "Grilled lamb cutlets, escalivada, fideuà, Garrotxa goat cheese, pan con tomate.",
  },
  // DOURO VALLEY
  {
    id: "wine-quinta-do-noval-vintage-port-2017",
    name: "Quinta do Noval Vintage Port 2017",
    producer: "Quinta do Noval",
    producerId: "prod-quinta-do-noval",
    vintage: 2017,
    grapes: ["Touriga Nacional", "Touriga Franca", "Tinta Roriz", "Tinto Cão"],
    region: "Douro Valley",
    country: "Portugal",
    appellation: "Porto DOC",
    type: "fortified",
    priceRange: "premium",
    description: "Declared Vintage Port from one of the Douro's most historic quintas, combining power with refined elegance.",
    tastingNotes: "Blackberry preserve, dark chocolate, violet, clove, and graphite. Concentrated and sweet with firm tannins and a long, warming finish.",
    foodPairing: "Stilton cheese, dark chocolate torte, roasted walnuts, crème brûlée.",
  },
  {
    id: "wine-niepoort-batuta-2019",
    name: "Niepoort Batuta 2019",
    producer: "Niepoort",
    producerId: "prod-niepoort",
    vintage: 2019,
    grapes: ["Touriga Nacional", "Touriga Franca", "Tinta Amarela", "Tinta Roriz"],
    region: "Douro Valley",
    country: "Portugal",
    appellation: "Douro DOC",
    type: "red",
    priceRange: "premium",
    description: "Flagship dry Douro red from old vines, made in a Burgundian style with whole clusters and gentle extraction — Douro's answer to fine Pinot.",
    tastingNotes: "Wild raspberry, pomegranate, wet stone, dried herbs, and a hint of smoke. Elegant with silky tannins and vibrant, persistent acidity.",
    foodPairing: "Grilled sea bass, bacalhau à Brás, roasted duck, Serra da Estrela cheese.",
  },
  // ALENTEJO
  {
    id: "wine-esporao-reserva-2020",
    name: "Herdade do Esporão Reserva 2020",
    producer: "Herdade do Esporão",
    producerId: "prod-herdade-do-esporao",
    vintage: 2020,
    grapes: ["Aragonez", "Trincadeira", "Cabernet Sauvignon", "Alicante Bouschet"],
    region: "Alentejo",
    country: "Portugal",
    appellation: "Alentejo DOC",
    type: "red",
    priceRange: "mid",
    description: "Flagship Alentejo blend from a vast estate, showcasing southern Portugal's sun-drenched indigenous varieties at an exceptional value.",
    tastingNotes: "Ripe plum, fig, dark chocolate, dried herb, and warm spice. Full-bodied with round tannins and a generous, fruity finish.",
    foodPairing: "Grilled Ibérico pork, carne de porco à Alentejana, migas, aged São Jorge cheese.",
  },
  // MOSEL
  {
    id: "wine-egon-muller-scharzhofberger-spatlese-2021",
    name: "Egon Müller Scharzhofberger Riesling Spätlese 2021",
    producer: "Egon Müller",
    producerId: "prod-egon-muller",
    vintage: 2021,
    grapes: ["Riesling"],
    region: "Mosel",
    country: "Germany",
    appellation: "Mosel",
    type: "white",
    priceRange: "luxury",
    description: "From the world's most celebrated Riesling vineyard on the steep blue-slate slopes of the Saar, this Spätlese is crystalline perfection.",
    tastingNotes: "Green apple, white peach, wet slate, lime blossom, and a hint of honey. Featherweight body with electric acidity and extraordinary purity.",
    foodPairing: "Sashimi, Thai papaya salad, soft-shell crab, apricot tart, mild blue cheese.",
  },
  {
    id: "wine-jj-prum-wehlener-sonnenuhr-auslese-2020",
    name: "Joh. Jos. Prüm Wehlener Sonnenuhr Riesling Auslese 2020",
    producer: "Joh. Jos. Prüm",
    producerId: "prod-jj-prum",
    vintage: 2020,
    grapes: ["Riesling"],
    region: "Mosel",
    country: "Germany",
    appellation: "Mosel",
    type: "white",
    priceRange: "premium",
    description: "Auslese from the iconic sundial vineyard in Wehlen, where steep slate slopes produce Rieslings of legendary concentration and longevity.",
    tastingNotes: "Ripe peach, honey, petrol, crushed rock, and lime zest. Off-dry with piercing acidity that balances the residual sugar perfectly.",
    foodPairing: "Foie gras, Peking duck, spicy Sichuan dishes, tarte Tatin, washed-rind cheeses.",
  },
  // RHEINGAU
  {
    id: "wine-robert-weil-kiedrich-grafenberg-spatlese-2021",
    name: "Robert Weil Kiedrich Gräfenberg Riesling Spätlese 2021",
    producer: "Robert Weil",
    producerId: "prod-robert-weil",
    vintage: 2021,
    grapes: ["Riesling"],
    region: "Rheingau",
    country: "Germany",
    appellation: "Rheingau",
    type: "white",
    priceRange: "premium",
    description: "Aristocratic Spätlese from the Rheingau's finest vineyard site, combining Gräfenberg's depth with the Rheingau's signature fullness.",
    tastingNotes: "Yellow peach, quince, beeswax, slate, and white flowers. Medium-bodied with racy acidity and a long, honeyed mineral finish.",
    foodPairing: "Wiener Schnitzel, roast pork with apple sauce, Munster cheese, lobster thermidor.",
  },
  // AUSTRIA
  {
    id: "wine-fx-pichler-gruner-veltliner-kellerberg-2021",
    name: "F.X. Pichler Grüner Veltliner Smaragd Kellerberg 2021",
    producer: "F.X. Pichler",
    producerId: "prod-fx-pichler",
    vintage: 2021,
    grapes: ["Grüner Veltliner"],
    region: "Wachau",
    country: "Austria",
    appellation: "Wachau DAC",
    type: "white",
    priceRange: "premium",
    description: "Austria's greatest dry white wine from the steep Kellerberg terraces above the Danube — monumentally powerful Grüner Veltliner.",
    tastingNotes: "White pepper, ripe pear, grapefruit, smoke, and herbal notes. Full-bodied with a creamy texture, racy acidity, and mineral depth.",
    foodPairing: "Wiener Schnitzel, asparagus with hollandaise, grilled river trout, Tafelspitz, sheep cheese.",
  },
];

export const wineries = [
  // RIOJA
  { name: "López de Heredia", slug: "lopez-de-heredia", description: "Time stands still here. Wines aged for decades in barrel, unchanged since 1877.", founded: 1877, owner: "López de Heredia Family", region: "Rioja", country: "Spain", lat: 42.5844, lng: -2.8485, grapeVarieties: ["Tempranillo", "Garnacha", "Viura"], wineStyles: ["red", "white", "rosé"], featured: true, vineyardSize: "170 hectares", annualBottles: 400000 },
  { name: "La Rioja Alta", slug: "la-rioja-alta", description: "One of Rioja's most respected bodegas, renowned for classic, long-aged reservas and gran reservas.", founded: 1890, owner: "Shareholders", region: "Rioja", country: "Spain", lat: 42.5831, lng: -2.8507, grapeVarieties: ["Tempranillo", "Graciano", "Mazuelo"], wineStyles: ["red"], featured: false, vineyardSize: "425 hectares", annualBottles: 3000000 },
  // RIBERA DEL DUERO
  { name: "Vega Sicilia", slug: "vega-sicilia", description: "Spain's most iconic winery, producing Único since 1915.", founded: 1864, owner: "Álvarez Family", region: "Ribera del Duero", country: "Spain", lat: 41.640, lng: -4.269, grapeVarieties: ["Tempranillo", "Cabernet Sauvignon"], wineStyles: ["red"], featured: true, vineyardSize: "210 hectares", annualBottles: 300000 },
  // PRIORAT
  { name: "Álvaro Palacios", slug: "alvaro-palacios", description: "The visionary who revived Priorat, creating L'Ermita from ancient Garnacha on steep llicorella slate.", founded: 1989, owner: "Álvaro Palacios", region: "Priorat", country: "Spain", lat: 41.1851, lng: 0.7526, grapeVarieties: ["Garnacha", "Cariñena", "Cabernet Sauvignon"], wineStyles: ["red"], featured: true, vineyardSize: "30 hectares", annualBottles: 250000 },
  // DOURO VALLEY
  { name: "Quinta do Noval", slug: "quinta-do-noval", description: "Home of Nacional, the world's rarest port from ungrafted vines.", founded: 1715, owner: "AXA Millésimes", region: "Douro Valley", country: "Portugal", lat: 41.145, lng: -7.525, grapeVarieties: ["Touriga Nacional", "Touriga Franca"], wineStyles: ["red", "fortified"], featured: true, vineyardSize: "145 hectares", annualBottles: 250000 },
  { name: "Niepoort", slug: "niepoort", description: "Fifth-generation Port house that helped pioneer the Douro's transformation into a dry wine region.", founded: 1842, owner: "Dirk Niepoort", region: "Douro Valley", country: "Portugal", lat: 41.1083, lng: -7.7328, grapeVarieties: ["Touriga Nacional", "Touriga Franca", "Tinta Roriz"], wineStyles: ["red", "fortified", "white"], featured: false, vineyardSize: "65 hectares", annualBottles: 600000 },
  // ALENTEJO
  { name: "Herdade do Esporão", slug: "herdade-do-esporao", description: "Vast Alentejo estate blending ancient heritage with modern sustainability.", founded: 1267, owner: "Roquette Family", region: "Alentejo", country: "Portugal", lat: 38.3808, lng: -7.5869, grapeVarieties: ["Aragonez", "Trincadeira", "Alicante Bouschet"], wineStyles: ["red", "white"], featured: false, vineyardSize: "700 hectares", annualBottles: 7000000 },
  // MOSEL
  { name: "Egon Müller", slug: "egon-muller", description: "Producer of the world's most expensive white wine from the steep slate slopes above the Saar.", founded: 1797, owner: "Egon Müller IV", region: "Mosel", country: "Germany", lat: 49.6890, lng: 6.5740, grapeVarieties: ["Riesling"], wineStyles: ["white"], featured: true, vineyardSize: "12 hectares", annualBottles: 70000 },
  { name: "Joh. Jos. Prüm", slug: "jj-prum", description: "The quintessential Mosel estate, producing crystalline Rieslings from the famed Wehlener Sonnenuhr.", founded: 1911, owner: "Prüm Family", region: "Mosel", country: "Germany", lat: 49.9396, lng: 7.0614, grapeVarieties: ["Riesling"], wineStyles: ["white"], featured: true, vineyardSize: "20 hectares", annualBottles: 120000 },
  // RHEINGAU
  { name: "Robert Weil", slug: "robert-weil", description: "Rheingau's premier estate, producing aristocratic Rieslings from the Kiedrich Gräfenberg vineyard.", founded: 1875, owner: "Suntory Holdings", region: "Rheingau", country: "Germany", lat: 50.0446, lng: 8.0857, grapeVarieties: ["Riesling"], wineStyles: ["white"], featured: true, vineyardSize: "90 hectares", annualBottles: 500000 },
  // AUSTRIA (Wachau is not a mapped region — pin won't render on map but data is still valuable)
  { name: "F.X. Pichler", slug: "fx-pichler", description: "Austria's most celebrated winery, producing monumentally powerful dry Rieslings and Grüner Veltliners.", founded: 1898, owner: "Lucas Pichler", region: "Wachau", country: "Austria", lat: 48.3689, lng: 15.4233, grapeVarieties: ["Grüner Veltliner", "Riesling"], wineStyles: ["white"], featured: true, vineyardSize: "17 hectares", annualBottles: 80000 },
];
