/**
 * France — curated seed data.
 * Covers: Bordeaux, Burgundy, Champagne, Rhone Valley, Loire Valley, Alsace, Provence
 */

export const producers = [
  // BORDEAUX
  {
    id: "prod-chateau-margaux",
    name: "Château Margaux",
    country: "France",
    region: "Bordeaux",
    website: "https://www.chateau-margaux.com",
    foundedYear: 1590,
    description: "Premier Grand Cru Classé estate in the Margaux appellation, producing one of the world's most elegant and perfumed Bordeaux wines since the 16th century.",
  },
  {
    id: "prod-chateau-lafite",
    name: "Château Lafite Rothschild",
    country: "France",
    region: "Bordeaux",
    website: "https://www.lafite.com",
    foundedYear: 1234,
    description: "First Growth estate in Pauillac and epitome of Bordeaux finesse, owned by the Rothschild family since 1868.",
  },
  {
    id: "prod-petrus",
    name: "Pétrus",
    country: "France",
    region: "Bordeaux",
    website: null,
    foundedYear: 1837,
    description: "Legendary Pomerol estate on a unique clay plateau, producing one of the most sought-after Merlot-dominant wines in the world.",
  },
  {
    id: "prod-chateau-dyquem",
    name: "Château d'Yquem",
    country: "France",
    region: "Bordeaux",
    website: "https://www.yquem.fr",
    foundedYear: 1593,
    description: "The only Premier Cru Supérieur in the 1855 Classification, producing the world's most revered Sauternes dessert wine.",
  },
  // BURGUNDY
  {
    id: "prod-drc",
    name: "Domaine de la Romanée-Conti",
    country: "France",
    region: "Burgundy",
    website: null,
    foundedYear: 1232,
    description: "The most prestigious wine estate on earth, producing vanishingly small quantities of transcendent Pinot Noir and Chardonnay from Grand Cru vineyards in Vosne-Romanée.",
  },
  {
    id: "prod-louis-jadot",
    name: "Louis Jadot",
    country: "France",
    region: "Burgundy",
    website: "https://www.louisjadot.com",
    foundedYear: 1859,
    description: "Major Burgundy négociant-éleveur with an exceptional portfolio spanning village, Premier Cru, and Grand Cru vineyards across the Côte d'Or.",
  },
  {
    id: "prod-domaine-leflaive",
    name: "Domaine Leflaive",
    country: "France",
    region: "Burgundy",
    website: "https://www.leflaive.fr",
    foundedYear: 1717,
    description: "Puligny-Montrachet estate widely regarded as the greatest white Burgundy producer, pioneering biodynamic viticulture in the region.",
  },
  // CHAMPAGNE
  {
    id: "prod-dom-perignon",
    name: "Dom Pérignon",
    country: "France",
    region: "Champagne",
    website: "https://www.domperignon.com",
    foundedYear: 1936,
    description: "Moët & Chandon's prestige cuvée, named after the Benedictine monk who pioneered blending techniques in Champagne.",
  },
  {
    id: "prod-krug",
    name: "Krug",
    country: "France",
    region: "Champagne",
    website: "https://www.krug.com",
    foundedYear: 1843,
    description: "The most individualistic of the great Champagne houses, known for barrel-fermented, deeply complex multi-vintage blends.",
  },
  {
    id: "prod-bollinger",
    name: "Bollinger",
    country: "France",
    region: "Champagne",
    website: "https://www.champagne-bollinger.com",
    foundedYear: 1829,
    description: "Family-owned Champagne house in Aÿ, celebrated for its rich, Pinot Noir-driven style and extensive reserve wine library.",
  },
  // RHONE VALLEY
  {
    id: "prod-guigal",
    name: "E. Guigal",
    country: "France",
    region: "Rhone Valley",
    website: "https://www.guigal.com",
    foundedYear: 1946,
    description: "Northern Rhône powerhouse producing the legendary single-vineyard Côte-Rôties — La Mouline, La Landonne, and La Turque.",
  },
  {
    id: "prod-chapoutier",
    name: "M. Chapoutier",
    country: "France",
    region: "Rhone Valley",
    website: "https://www.chapoutier.com",
    foundedYear: 1808,
    description: "Pioneering biodynamic Rhône producer with exceptional Hermitage holdings, known for opulent Syrah and Marsanne wines.",
  },
  // LOIRE VALLEY
  {
    id: "prod-domaine-huet",
    name: "Domaine Huet",
    country: "France",
    region: "Loire Valley",
    website: "https://www.huet-echansonne.com",
    foundedYear: 1928,
    description: "The benchmark Vouvray estate, producing extraordinary Chenin Blanc in dry, demi-sec, and moelleux styles from biodynamic vineyards.",
  },
  // ALSACE
  {
    id: "prod-trimbach",
    name: "Trimbach",
    country: "France",
    region: "Alsace",
    website: "https://www.trimbach.fr",
    foundedYear: 1626,
    description: "Iconic Alsatian house producing bone-dry, mineral Rieslings for nearly four centuries, including the legendary Clos Sainte Hune.",
  },
  // PROVENCE
  {
    id: "prod-domaines-ott",
    name: "Domaines Ott",
    country: "France",
    region: "Provence",
    website: "https://www.domaines-ott.com",
    foundedYear: 1912,
    description: "The pioneer of premium Provençal rosé, producing benchmark pale, elegant wines from three estates across Provence.",
  },
];

export const wines = [
  // BORDEAUX
  {
    id: "wine-chateau-margaux-2019",
    name: "Château Margaux 2019",
    producer: "Château Margaux",
    producerId: "prod-chateau-margaux",
    vintage: 2019,
    grapes: ["Cabernet Sauvignon", "Merlot", "Petit Verdot", "Cabernet Franc"],
    region: "Bordeaux",
    country: "France",
    appellation: "Margaux AOC",
    type: "red",
    priceRange: "luxury",
    description: "A benchmark Left Bank Bordeaux combining power and ethereal elegance from one of the greatest modern vintages.",
    tastingNotes: "Blackcurrant, crushed violets, cedar, graphite, and subtle smoke. Silky tannins with extraordinary length and precision.",
    foodPairing: "Grilled rack of lamb with rosemary, aged Comté cheese, roasted duck breast with truffle jus.",
  },
  {
    id: "wine-chateau-lafite-2018",
    name: "Château Lafite Rothschild 2018",
    producer: "Château Lafite Rothschild",
    producerId: "prod-chateau-lafite",
    vintage: 2018,
    grapes: ["Cabernet Sauvignon", "Merlot", "Cabernet Franc"],
    region: "Bordeaux",
    country: "France",
    appellation: "Pauillac AOC",
    type: "red",
    priceRange: "luxury",
    description: "Classic Pauillac First Growth showing immense depth and refinement from an exceptional vintage on the Left Bank.",
    tastingNotes: "Lead pencil, blackberry, cassis, and dried roses. Fine-grained tannins frame a core of pure dark fruit with a mineral finish.",
    foodPairing: "Filet of beef with Périgueux sauce, slow-braised short ribs, Époisses cheese.",
  },
  {
    id: "wine-petrus-2018",
    name: "Pétrus 2018",
    producer: "Pétrus",
    producerId: "prod-petrus",
    vintage: 2018,
    grapes: ["Merlot"],
    region: "Bordeaux",
    country: "France",
    appellation: "Pomerol AOC",
    type: "red",
    priceRange: "luxury",
    description: "Pure Merlot from the famed clay plateau of Pomerol, one of the most concentrated and long-lived wines in the world.",
    tastingNotes: "Black truffle, plum compote, mocha, wet clay, and violets. Velvet texture with immense concentration and a seemingly endless finish.",
    foodPairing: "Pan-seared foie gras, roasted venison with blackberry reduction, black truffle risotto.",
  },
  {
    id: "wine-chateau-dyquem-2017",
    name: "Château d'Yquem 2017",
    producer: "Château d'Yquem",
    producerId: "prod-chateau-dyquem",
    vintage: 2017,
    grapes: ["Sémillon", "Sauvignon Blanc"],
    region: "Bordeaux",
    country: "France",
    appellation: "Sauternes AOC",
    type: "dessert",
    priceRange: "luxury",
    description: "The world's greatest sweet wine, made from botrytized grapes hand-picked in multiple passes over several weeks.",
    tastingNotes: "Saffron, apricot, honey, candied orange peel, and crème brûlée. Electrifying acidity balances luscious sweetness with a finish lasting minutes.",
    foodPairing: "Roquefort cheese, foie gras terrine, tarte tatin, tropical fruit pavlova.",
  },
  // BURGUNDY
  {
    id: "wine-drc-romanee-conti-2019",
    name: "Romanée-Conti Grand Cru 2019",
    producer: "Domaine de la Romanée-Conti",
    producerId: "prod-drc",
    vintage: 2019,
    grapes: ["Pinot Noir"],
    region: "Burgundy",
    country: "France",
    appellation: "Romanée-Conti Grand Cru",
    type: "red",
    priceRange: "luxury",
    description: "The most expensive and coveted wine on earth from a 1.81-hectare monopole vineyard in Vosne-Romanée.",
    tastingNotes: "Rose petals, wild strawberry, spice, earth, and an ineffable complexity that defies description. Gossamer tannins with transcendent purity.",
    foodPairing: "Roasted squab with morel mushrooms, Bresse chicken with black truffles, aged Brillat-Savarin.",
  },
  {
    id: "wine-jadot-gevrey-chambertin-2020",
    name: "Louis Jadot Gevrey-Chambertin 2020",
    producer: "Louis Jadot",
    producerId: "prod-louis-jadot",
    vintage: 2020,
    grapes: ["Pinot Noir"],
    region: "Burgundy",
    country: "France",
    appellation: "Gevrey-Chambertin AOC",
    type: "red",
    priceRange: "premium",
    description: "A structured, serious village-level Burgundy from the most prestigious commune of the Côte de Nuits.",
    tastingNotes: "Dark cherry, blackcurrant, licorice, and earthy undertones. Firm tannins with a long, spicy finish.",
    foodPairing: "Coq au vin, beef bourguignon, aged Gruyère, mushroom risotto.",
  },
  {
    id: "wine-leflaive-puligny-montrachet-2021",
    name: "Domaine Leflaive Puligny-Montrachet 2021",
    producer: "Domaine Leflaive",
    producerId: "prod-domaine-leflaive",
    vintage: 2021,
    grapes: ["Chardonnay"],
    region: "Burgundy",
    country: "France",
    appellation: "Puligny-Montrachet AOC",
    type: "white",
    priceRange: "premium",
    description: "Benchmark white Burgundy from the greatest Chardonnay village, biodynamically farmed with crystalline precision.",
    tastingNotes: "Citrus blossom, green apple, flint, and hazelnut. Taut acidity with a chalky mineral texture and long saline finish.",
    foodPairing: "Lobster thermidor, Dover sole meunière, goat cheese soufflé, asparagus with hollandaise.",
  },
  // CHAMPAGNE
  {
    id: "wine-dom-perignon-2013",
    name: "Dom Pérignon Vintage 2013",
    producer: "Dom Pérignon",
    producerId: "prod-dom-perignon",
    vintage: 2013,
    grapes: ["Chardonnay", "Pinot Noir"],
    region: "Champagne",
    country: "France",
    appellation: "Champagne AOC",
    type: "sparkling",
    priceRange: "luxury",
    description: "Prestige cuvée Champagne from a challenging vintage that produced wines of remarkable tension and energy.",
    tastingNotes: "White peach, almond, brioche, citrus zest, and chalky minerality. Fine mousse with a vibrant, driven finish.",
    foodPairing: "Oysters, seared scallops with cauliflower purée, smoked salmon blinis, Parmesan aged 36 months.",
  },
  {
    id: "wine-krug-grande-cuvee",
    name: "Krug Grande Cuvée",
    producer: "Krug",
    producerId: "prod-krug",
    vintage: null,
    grapes: ["Pinot Noir", "Chardonnay", "Pinot Meunier"],
    region: "Champagne",
    country: "France",
    appellation: "Champagne AOC",
    type: "sparkling",
    priceRange: "luxury",
    description: "The flagship multi-vintage blend, crafted from over 120 wines spanning more than 10 vintages for unmatched complexity.",
    tastingNotes: "Toasted hazelnut, dried apricot, honey, marzipan, and biscuit. Creamy mousse with extraordinary depth and a long, spiced finish.",
    foodPairing: "Langoustines, truffle pasta, fried chicken, aged Comté, mushroom tart.",
  },
  {
    id: "wine-bollinger-special-cuvee",
    name: "Bollinger Special Cuvée",
    producer: "Bollinger",
    producerId: "prod-bollinger",
    vintage: null,
    grapes: ["Pinot Noir", "Chardonnay", "Pinot Meunier"],
    region: "Champagne",
    country: "France",
    appellation: "Champagne AOC",
    type: "sparkling",
    priceRange: "premium",
    description: "The house's signature non-vintage blend, built on Pinot Noir from Grand Cru villages and extensive reserve wines aged in magnums.",
    tastingNotes: "Ripe pear, toasted brioche, walnut, and spice. Full-bodied with a persistent, creamy mousse and a warm, generous finish.",
    foodPairing: "Roast chicken, fish and chips, charcuterie, Brie de Meaux, gougères.",
  },
  // RHONE VALLEY
  {
    id: "wine-guigal-cote-rotie-la-mouline-2018",
    name: "E. Guigal Côte-Rôtie La Mouline 2018",
    producer: "E. Guigal",
    producerId: "prod-guigal",
    vintage: 2018,
    grapes: ["Syrah", "Viognier"],
    region: "Rhone Valley",
    country: "France",
    appellation: "Côte-Rôtie AOC",
    type: "red",
    priceRange: "luxury",
    description: "One of three legendary single-vineyard Côte-Rôties, La Mouline is the most perfumed and seductive of the 'LaLaLa' trio.",
    tastingNotes: "Violet, black raspberry, bacon fat, apricot, and smoky oak. Opulent texture with velvety tannins and an exotic, lingering finish.",
    foodPairing: "Braised lamb shoulder, grilled pigeon, cassoulet, Roquefort cheese.",
  },
  {
    id: "wine-chapoutier-hermitage-2019",
    name: "M. Chapoutier Ermitage Le Méal 2019",
    producer: "M. Chapoutier",
    producerId: "prod-chapoutier",
    vintage: 2019,
    grapes: ["Syrah"],
    region: "Rhone Valley",
    country: "France",
    appellation: "Hermitage AOC",
    type: "red",
    priceRange: "luxury",
    description: "Single-vineyard Hermitage from the sun-drenched Le Méal lieu-dit, biodynamically farmed and one of the northern Rhône's greatest reds.",
    tastingNotes: "Blackberry, smoked meat, crushed rock, dark chocolate, and garrigue herbs. Massive yet refined with granite-like minerality.",
    foodPairing: "Grilled rib-eye steak, venison with juniper berry sauce, aged Cantal cheese.",
  },
  // LOIRE VALLEY
  {
    id: "wine-huet-vouvray-le-haut-lieu-2020",
    name: "Domaine Huet Vouvray Le Haut-Lieu Sec 2020",
    producer: "Domaine Huet",
    producerId: "prod-domaine-huet",
    vintage: 2020,
    grapes: ["Chenin Blanc"],
    region: "Loire Valley",
    country: "France",
    appellation: "Vouvray AOC",
    type: "white",
    priceRange: "mid",
    description: "Benchmark dry Vouvray from a premier biodynamic estate, showcasing the extraordinary versatility of Chenin Blanc.",
    tastingNotes: "Quince, beeswax, chamomile, wet stone, and honey. Concentrated with rapier-like acidity and a long, mineral finish.",
    foodPairing: "River fish with beurre blanc, goat cheese salad, pork rillettes, Thai green curry.",
  },
  // ALSACE
  {
    id: "wine-trimbach-riesling-clos-ste-hune-2018",
    name: "Trimbach Riesling Clos Sainte Hune 2018",
    producer: "Trimbach",
    producerId: "prod-trimbach",
    vintage: 2018,
    grapes: ["Riesling"],
    region: "Alsace",
    country: "France",
    appellation: "Alsace AOC",
    type: "white",
    priceRange: "luxury",
    description: "France's most famous single-vineyard Riesling, from a tiny plot within Grand Cru Rosacker, bone-dry with immense aging potential.",
    tastingNotes: "Lime, white peach, petrol, flint, and a saline minerality. Laser-like acidity with extraordinary concentration and purity.",
    foodPairing: "Choucroute garnie, lobster, sushi and sashimi, Munster cheese, smoked trout.",
  },
  // PROVENCE
  {
    id: "wine-domaines-ott-chateau-de-selle-2023",
    name: "Domaines Ott Château de Selle Rosé 2023",
    producer: "Domaines Ott",
    producerId: "prod-domaines-ott",
    vintage: 2023,
    grapes: ["Grenache", "Cinsault", "Cabernet Sauvignon"],
    region: "Provence",
    country: "France",
    appellation: "Côtes de Provence AOC",
    type: "rosé",
    priceRange: "premium",
    description: "The original prestige Provençal rosé, setting the standard for elegant, pale, gastronomic pink wine since 1912.",
    tastingNotes: "White peach, wild strawberry, citrus blossom, and a hint of garrigue herbs. Crisp and mineral with a delicate, silky texture.",
    foodPairing: "Grilled Mediterranean sea bass, bouillabaisse, Niçoise salad, fresh burrata with heirloom tomatoes.",
  },
];

export const wineries = [
  // BORDEAUX
  { name: "Château Margaux", slug: "chateau-margaux", description: "Premier Grand Cru Classé producing one of the world's most elegant wines since the 16th century.", founded: 1590, owner: "Corinne Mentzelopoulos", region: "Bordeaux", country: "France", lat: 45.0444, lng: -0.6687, grapeVarieties: ["Cabernet Sauvignon", "Merlot", "Petit Verdot"], wineStyles: ["red"], featured: true, vineyardSize: "87 hectares", annualBottles: 130000 },
  { name: "Château Lafite Rothschild", slug: "chateau-lafite", description: "First Growth estate in Pauillac, epitome of finesse and longevity.", founded: 1234, owner: "Domaines Barons de Rothschild", region: "Bordeaux", country: "France", lat: 45.2217, lng: -0.7705, grapeVarieties: ["Cabernet Sauvignon", "Merlot"], wineStyles: ["red"], featured: true, vineyardSize: "112 hectares", annualBottles: 200000 },
  { name: "Pétrus", slug: "petrus", description: "Legendary Pomerol estate on a unique clay plateau, producing one of the most sought-after Merlot-dominant wines in the world.", founded: 1837, owner: "Moueix Family", region: "Bordeaux", country: "France", lat: 44.9283, lng: -0.1864, grapeVarieties: ["Merlot"], wineStyles: ["red"], featured: true, vineyardSize: "11.5 hectares", annualBottles: 30000 },
  { name: "Château d'Yquem", slug: "chateau-dyquem", description: "The only Premier Cru Supérieur in the 1855 Classification, producing the world's most revered sweet wine.", founded: 1593, owner: "LVMH", region: "Bordeaux", country: "France", lat: 44.5402, lng: -0.3036, grapeVarieties: ["Sémillon", "Sauvignon Blanc"], wineStyles: ["dessert"], featured: true, vineyardSize: "113 hectares", annualBottles: 65000 },
  // BURGUNDY
  { name: "Domaine de la Romanée-Conti", slug: "drc", description: "The most prestigious wine estate on earth, producing tiny quantities of transcendent Pinot Noir.", founded: 1232, owner: "de Villaine & Leroy Families", region: "Burgundy", country: "France", lat: 47.1570, lng: 4.9500, grapeVarieties: ["Pinot Noir", "Chardonnay"], wineStyles: ["red", "white"], featured: true, vineyardSize: "28 hectares", annualBottles: 80000 },
  { name: "Louis Jadot", slug: "louis-jadot", description: "Major Burgundy négociant-éleveur with holdings across the region's finest vineyards.", founded: 1859, owner: "Kopf Family", region: "Burgundy", country: "France", lat: 47.0376, lng: 4.8406, grapeVarieties: ["Pinot Noir", "Chardonnay"], wineStyles: ["red", "white"], featured: false, vineyardSize: "240 hectares", annualBottles: 1200000 },
  { name: "Domaine Leflaive", slug: "domaine-leflaive", description: "Puligny-Montrachet estate widely regarded as the greatest white Burgundy producer.", founded: 1717, owner: "Leflaive Family", region: "Burgundy", country: "France", lat: 46.9505, lng: 4.7540, grapeVarieties: ["Chardonnay"], wineStyles: ["white"], featured: true, vineyardSize: "25 hectares", annualBottles: 100000 },
  // CHAMPAGNE
  { name: "Dom Pérignon", slug: "dom-perignon", description: "Moët & Chandon's prestige cuvée, named after the legendary monk.", founded: 1936, owner: "LVMH", region: "Champagne", country: "France", lat: 49.083, lng: 3.947, grapeVarieties: ["Chardonnay", "Pinot Noir"], wineStyles: ["sparkling"], featured: true, vineyardSize: "N/A", annualBottles: 5000000 },
  { name: "Krug", slug: "krug", description: "The most individualistic Champagne house, known for barrel-fermented, deeply complex multi-vintage blends.", founded: 1843, owner: "LVMH", region: "Champagne", country: "France", lat: 49.0485, lng: 3.9504, grapeVarieties: ["Pinot Noir", "Chardonnay", "Pinot Meunier"], wineStyles: ["sparkling"], featured: true, vineyardSize: "20 hectares", annualBottles: 600000 },
  { name: "Bollinger", slug: "bollinger", description: "Family-owned Champagne house in Aÿ, celebrated for its rich, Pinot Noir-driven style.", founded: 1829, owner: "Bollinger Family", region: "Champagne", country: "France", lat: 49.055, lng: 3.982, grapeVarieties: ["Pinot Noir", "Chardonnay", "Pinot Meunier"], wineStyles: ["sparkling"], featured: false, vineyardSize: "178 hectares", annualBottles: 3000000 },
  // RHONE VALLEY
  { name: "E. Guigal", slug: "guigal", description: "Northern Rhône powerhouse producing the legendary single-vineyard Côte-Rôties — La Mouline, La Landonne, and La Turque.", founded: 1946, owner: "Guigal Family", region: "Rhone Valley", country: "France", lat: 45.4714, lng: 4.8113, grapeVarieties: ["Syrah", "Viognier"], wineStyles: ["red", "white"], featured: true, vineyardSize: "60 hectares", annualBottles: 6000000 },
  { name: "M. Chapoutier", slug: "chapoutier", description: "Pioneering biodynamic Rhône producer with exceptional Hermitage holdings.", founded: 1808, owner: "Michel Chapoutier", region: "Rhone Valley", country: "France", lat: 45.0709, lng: 4.8356, grapeVarieties: ["Syrah", "Grenache", "Marsanne"], wineStyles: ["red", "white"], featured: false, vineyardSize: "350 hectares", annualBottles: 8000000 },
  // LOIRE VALLEY
  { name: "Domaine Huet", slug: "domaine-huet", description: "The benchmark Vouvray estate, producing extraordinary Chenin Blanc in dry, demi-sec, and moelleux styles.", founded: 1928, owner: "Hwang Family", region: "Loire Valley", country: "France", lat: 47.3731, lng: 0.8256, grapeVarieties: ["Chenin Blanc"], wineStyles: ["white"], featured: true, vineyardSize: "35 hectares", annualBottles: 150000 },
  // ALSACE
  { name: "Trimbach", slug: "trimbach", description: "Iconic Alsatian house producing bone-dry, mineral Rieslings for nearly four centuries.", founded: 1626, owner: "Trimbach Family", region: "Alsace", country: "France", lat: 48.1931, lng: 7.3164, grapeVarieties: ["Riesling", "Gewürztraminer", "Pinot Gris"], wineStyles: ["white"], featured: true, vineyardSize: "40 hectares", annualBottles: 1000000 },
  // PROVENCE
  { name: "Domaines Ott", slug: "domaines-ott", description: "The pioneer of premium Provençal rosé, producing benchmark pale, elegant wines from three estates.", founded: 1912, owner: "Roederer Group", region: "Provence", country: "France", lat: 43.4312, lng: 6.2563, grapeVarieties: ["Grenache", "Cinsault", "Cabernet Sauvignon"], wineStyles: ["rosé", "white", "red"], featured: true, vineyardSize: "100 hectares", annualBottles: 800000 },
];
