/**
 * Italy — curated seed data.
 * Covers: Piedmont, Tuscany, Veneto, Sicily
 */

export const producers = [
  // PIEDMONT
  {
    id: "prod-gaja",
    name: "Gaja",
    country: "Italy",
    region: "Piedmont",
    website: "https://www.gaja.com",
    foundedYear: 1859,
    description: "Angelo Gaja revolutionized Barbaresco and put Piedmont on the world stage with his uncompromising pursuit of quality and innovation.",
  },
  {
    id: "prod-giacomo-conterno",
    name: "Giacomo Conterno",
    country: "Italy",
    region: "Piedmont",
    website: null,
    foundedYear: 1908,
    description: "The most traditional Barolo producer, renowned for Monfortino — a Riserva that ages for decades and epitomizes Nebbiolo's grandeur.",
  },
  {
    id: "prod-bruno-giacosa",
    name: "Bruno Giacosa",
    country: "Italy",
    region: "Piedmont",
    website: "https://www.brunogiacosa.it",
    foundedYear: 1900,
    description: "Legendary Barolo and Barbaresco producer whose red-label Riservas are among the most sought-after wines in Italy.",
  },
  // TUSCANY
  {
    id: "prod-tenuta-san-guido",
    name: "Tenuta San Guido",
    country: "Italy",
    region: "Tuscany",
    website: "https://www.tenutasanguido.com",
    foundedYear: 1944,
    description: "Home of Sassicaia, the original Super Tuscan that single-handedly changed the trajectory of Italian fine wine.",
  },
  {
    id: "prod-antinori",
    name: "Antinori",
    country: "Italy",
    region: "Tuscany",
    website: "https://www.antinori.it",
    foundedYear: 1385,
    description: "Twenty-six generations of winemaking excellence, creators of Tignanello and Solaia, and one of the most influential families in wine.",
  },
  {
    id: "prod-biondi-santi",
    name: "Biondi-Santi",
    country: "Italy",
    region: "Tuscany",
    website: "https://www.biondisanti.it",
    foundedYear: 1888,
    description: "The founding estate of Brunello di Montalcino, with a Riserva library stretching back to 1888 — pure Sangiovese at its most austere.",
  },
  // VENETO
  {
    id: "prod-allegrini",
    name: "Allegrini",
    country: "Italy",
    region: "Veneto",
    website: "https://www.allegrini.it",
    foundedYear: 1557,
    description: "Historic Valpolicella estate producing benchmark Amarone and the iconic single-vineyard La Poja from pure Corvina Veronese.",
  },
  {
    id: "prod-quintarelli",
    name: "Giuseppe Quintarelli",
    country: "Italy",
    region: "Veneto",
    website: null,
    foundedYear: 1924,
    description: "The legendary artisan of Valpolicella, whose hand-labeled Amarones are released years after the vintage and fetch cult prices.",
  },
  // SICILY
  {
    id: "prod-planeta",
    name: "Planeta",
    country: "Italy",
    region: "Sicily",
    website: "https://www.planeta.it",
    foundedYear: 1995,
    description: "Sicily's most dynamic wine family, with estates across the island showcasing indigenous varieties alongside international grapes.",
  },
  {
    id: "prod-tasca-dalmerita",
    name: "Tasca d'Almerita",
    country: "Italy",
    region: "Sicily",
    website: "https://www.tascadalmerita.it",
    foundedYear: 1830,
    description: "Historic Sicilian estate at Regaleali, pioneering quality winemaking on the island for nearly two centuries with Nero d'Avola and Grillo.",
  },
];

export const wines = [
  // PIEDMONT
  {
    id: "wine-gaja-barbaresco-2019",
    name: "Gaja Barbaresco 2019",
    producer: "Gaja",
    producerId: "prod-gaja",
    vintage: 2019,
    grapes: ["Nebbiolo"],
    region: "Piedmont",
    country: "Italy",
    appellation: "Barbaresco DOCG",
    type: "red",
    priceRange: "luxury",
    description: "The benchmark Barbaresco — Angelo Gaja's flagship wine that redefined the appellation and proved Nebbiolo's place among the world's greatest grapes.",
    tastingNotes: "Tar, roses, wild cherry, leather, and licorice. Powerful tannins with an ethereal elegance and remarkable persistence.",
    foodPairing: "Braised beef cheeks, white truffle risotto, tajarin pasta with butter and sage, aged Parmigiano-Reggiano.",
  },
  {
    id: "wine-conterno-monfortino-2015",
    name: "Giacomo Conterno Monfortino Barolo Riserva 2015",
    producer: "Giacomo Conterno",
    producerId: "prod-giacomo-conterno",
    vintage: 2015,
    grapes: ["Nebbiolo"],
    region: "Piedmont",
    country: "Italy",
    appellation: "Barolo DOCG",
    type: "red",
    priceRange: "luxury",
    description: "Italy's greatest wine, aged for seven years in large Slavonian oak botti. Only produced in exceptional vintages from the Cascina Francia vineyard.",
    tastingNotes: "Dried roses, cherry compote, tar, tobacco, earth, and exotic spice. Monumental tannins with decades of aging potential.",
    foodPairing: "Brasato al Barolo, fonduta with white truffles, bollito misto, aged Castelmagno cheese.",
  },
  {
    id: "wine-giacosa-barolo-falletto-2017",
    name: "Bruno Giacosa Barolo Falletto 2017",
    producer: "Bruno Giacosa",
    producerId: "prod-bruno-giacosa",
    vintage: 2017,
    grapes: ["Nebbiolo"],
    region: "Piedmont",
    country: "Italy",
    appellation: "Barolo DOCG",
    type: "red",
    priceRange: "luxury",
    description: "Single-vineyard Barolo from the prized Falletto cru in Serralunga d'Alba, combining power with Giacosa's signature classical elegance.",
    tastingNotes: "Rose petal, ripe cherry, menthol, iron, and sweet tobacco. Firm, refined tannins with a long, mineral-driven finish.",
    foodPairing: "Roasted guinea fowl, porcini mushroom risotto, vitello tonnato, fontina fondue.",
  },
  // TUSCANY
  {
    id: "wine-sassicaia-2019",
    name: "Sassicaia 2019",
    producer: "Tenuta San Guido",
    producerId: "prod-tenuta-san-guido",
    vintage: 2019,
    grapes: ["Cabernet Sauvignon", "Cabernet Franc"],
    region: "Tuscany",
    country: "Italy",
    appellation: "Bolgheri Sassicaia DOC",
    type: "red",
    priceRange: "luxury",
    description: "The original Super Tuscan and Italy's most iconic Cabernet blend, from coastal vineyards in Bolgheri that changed the course of Italian wine.",
    tastingNotes: "Blackcurrant, Mediterranean herbs, pencil lead, and sea breeze. Firm, polished tannins with a long, savory finish.",
    foodPairing: "Grilled Fiorentina T-bone, wild boar ragù, aged Pecorino Toscano, lamb with rosemary.",
  },
  {
    id: "wine-antinori-tignanello-2020",
    name: "Antinori Tignanello 2020",
    producer: "Antinori",
    producerId: "prod-antinori",
    vintage: 2020,
    grapes: ["Sangiovese", "Cabernet Sauvignon", "Cabernet Franc"],
    region: "Tuscany",
    country: "Italy",
    appellation: "Toscana IGT",
    type: "red",
    priceRange: "premium",
    description: "The wine that launched the Super Tuscan revolution in 1971 — Sangiovese blended with Cabernet and aged in French barriques.",
    tastingNotes: "Dark cherry, plum, espresso, vanilla, and tobacco leaf. Velvety tannins with a warm, persistent finish.",
    foodPairing: "Pappardelle with wild boar ragù, bistecca alla fiorentina, grilled lamb chops, aged Pecorino.",
  },
  {
    id: "wine-biondi-santi-brunello-riserva-2016",
    name: "Biondi-Santi Brunello di Montalcino Riserva 2016",
    producer: "Biondi-Santi",
    producerId: "prod-biondi-santi",
    vintage: 2016,
    grapes: ["Sangiovese"],
    region: "Tuscany",
    country: "Italy",
    appellation: "Brunello di Montalcino DOCG",
    type: "red",
    priceRange: "luxury",
    description: "The original Brunello, from the estate that invented the category. Only made in top vintages from vines over 25 years old.",
    tastingNotes: "Sour cherry, dried herb, tea leaf, orange peel, and leather. Austere tannins with extraordinary finesse and a decades-long aging arc.",
    foodPairing: "Slow-roasted pork loin, truffle-laced pici pasta, aged Pecorino di Pienza, grilled quail.",
  },
  // VENETO
  {
    id: "wine-allegrini-amarone-2018",
    name: "Allegrini Amarone della Valpolicella Classico 2018",
    producer: "Allegrini",
    producerId: "prod-allegrini",
    vintage: 2018,
    grapes: ["Corvina", "Rondinella", "Oseleta"],
    region: "Veneto",
    country: "Italy",
    appellation: "Amarone della Valpolicella DOCG",
    type: "red",
    priceRange: "premium",
    description: "Benchmark Amarone from appassimento-dried grapes, balancing the style's richness with elegance and freshness.",
    tastingNotes: "Black cherry, dried fig, dark chocolate, cinnamon, and coffee. Full-bodied with sweet, ripe tannins and a warm, spiced finish.",
    foodPairing: "Osso buco, braised short ribs, gorgonzola cheese, dark chocolate desserts.",
  },
  {
    id: "wine-quintarelli-amarone-2012",
    name: "Giuseppe Quintarelli Amarone della Valpolicella Classico 2012",
    producer: "Giuseppe Quintarelli",
    producerId: "prod-quintarelli",
    vintage: 2012,
    grapes: ["Corvina", "Rondinella", "Croatina", "Cabernet Sauvignon"],
    region: "Veneto",
    country: "Italy",
    appellation: "Amarone della Valpolicella DOCG",
    type: "red",
    priceRange: "luxury",
    description: "The cult Amarone, hand-labeled and released years after the vintage. Quintarelli's artisanal approach produces wines of unmatched depth.",
    tastingNotes: "Dried cherry, incense, soy sauce, dark spice, and tobacco. Concentrated and complex with a finish that evolves for minutes.",
    foodPairing: "Braised oxtail, aged Parmigiano-Reggiano 60 months, venison stew, dried fruit and nut pairings.",
  },
  // SICILY
  {
    id: "wine-planeta-santa-cecilia-2019",
    name: "Planeta Santa Cecilia 2019",
    producer: "Planeta",
    producerId: "prod-planeta",
    vintage: 2019,
    grapes: ["Nero d'Avola"],
    region: "Sicily",
    country: "Italy",
    appellation: "Noto DOC",
    type: "red",
    priceRange: "premium",
    description: "Single-vineyard Nero d'Avola from the south-eastern tip of Sicily, showcasing the island's most important red grape at its finest.",
    tastingNotes: "Ripe blackberry, Mediterranean herbs, carob, and dark chocolate. Full-bodied with warm, supple tannins and a sun-baked finish.",
    foodPairing: "Grilled swordfish, pasta alla Norma, arancini, caponata, aged Ragusano cheese.",
  },
  {
    id: "wine-tasca-rosso-del-conte-2018",
    name: "Tasca d'Almerita Rosso del Conte 2018",
    producer: "Tasca d'Almerita",
    producerId: "prod-tasca-dalmerita",
    vintage: 2018,
    grapes: ["Nero d'Avola", "Perricone"],
    region: "Sicily",
    country: "Italy",
    appellation: "Terre Siciliane IGT",
    type: "red",
    priceRange: "premium",
    description: "The flagship red from the historic Regaleali estate in central Sicily, first produced in 1970 and a benchmark for Sicilian fine wine.",
    tastingNotes: "Red cherry, blood orange, wild herbs, volcanic mineral, and sweet spice. Medium-bodied with fine tannins and vibrant acidity.",
    foodPairing: "Lamb with Sicilian oregano, pasta con le sarde, grilled tuna, cassata as dessert.",
  },
];

export const wineries = [
  // PIEDMONT
  { name: "Gaja", slug: "gaja", description: "Angelo Gaja revolutionized Barbaresco and put Piedmont on the world stage.", founded: 1859, owner: "Gaja Family", region: "Piedmont", country: "Italy", lat: 44.7275, lng: 8.0790, grapeVarieties: ["Nebbiolo", "Barbera", "Chardonnay"], wineStyles: ["red", "white"], featured: true, vineyardSize: "100 hectares", annualBottles: 350000 },
  { name: "Giacomo Conterno", slug: "giacomo-conterno", description: "The most traditional Barolo producer, Monfortino ages for decades.", founded: 1908, owner: "Roberto Conterno", region: "Piedmont", country: "Italy", lat: 44.636, lng: 7.971, grapeVarieties: ["Nebbiolo"], wineStyles: ["red"], featured: true, vineyardSize: "14 hectares", annualBottles: 60000 },
  { name: "Bruno Giacosa", slug: "bruno-giacosa", description: "Legendary Barolo and Barbaresco producer whose red-label Riservas are among Italy's most coveted wines.", founded: 1900, owner: "Bruna Giacosa", region: "Piedmont", country: "Italy", lat: 44.6865, lng: 8.0053, grapeVarieties: ["Nebbiolo"], wineStyles: ["red", "sparkling"], featured: true, vineyardSize: "20 hectares", annualBottles: 400000 },
  // TUSCANY
  { name: "Tenuta San Guido", slug: "tenuta-san-guido", description: "Home of Sassicaia, the original Super Tuscan that changed Italian wine.", founded: 1944, owner: "Incisa della Rocchetta Family", region: "Tuscany", country: "Italy", lat: 43.2064, lng: 10.5539, grapeVarieties: ["Cabernet Sauvignon", "Cabernet Franc"], wineStyles: ["red"], featured: true, vineyardSize: "75 hectares", annualBottles: 200000 },
  { name: "Antinori", slug: "antinori", description: "26 generations of winemaking, creators of Tignanello and Solaia.", founded: 1385, owner: "Antinori Family", region: "Tuscany", country: "Italy", lat: 43.6120, lng: 11.1916, grapeVarieties: ["Sangiovese", "Cabernet Sauvignon"], wineStyles: ["red", "white", "rosé"], featured: true, vineyardSize: "3000 hectares", annualBottles: 20000000 },
  { name: "Biondi-Santi", slug: "biondi-santi", description: "The founding estate of Brunello di Montalcino, with a Riserva library stretching back to 1888.", founded: 1888, owner: "EPI Group", region: "Tuscany", country: "Italy", lat: 43.0584, lng: 11.4816, grapeVarieties: ["Sangiovese"], wineStyles: ["red"], featured: true, vineyardSize: "25 hectares", annualBottles: 80000 },
  // VENETO
  { name: "Allegrini", slug: "allegrini", description: "Historic Valpolicella estate producing benchmark Amarone and the iconic single-vineyard La Poja.", founded: 1557, owner: "Allegrini Family", region: "Veneto", country: "Italy", lat: 45.5158, lng: 10.8776, grapeVarieties: ["Corvina", "Rondinella", "Oseleta"], wineStyles: ["red"], featured: false, vineyardSize: "100 hectares", annualBottles: 1000000 },
  { name: "Giuseppe Quintarelli", slug: "quintarelli", description: "The legendary artisan of Valpolicella, whose hand-labeled Amarones are released years after the vintage.", founded: 1924, owner: "Quintarelli Family", region: "Veneto", country: "Italy", lat: 45.5214, lng: 10.8926, grapeVarieties: ["Corvina", "Rondinella", "Molinara"], wineStyles: ["red"], featured: true, vineyardSize: "12 hectares", annualBottles: 50000 },
  // SICILY
  { name: "Planeta", slug: "planeta", description: "Sicily's most dynamic wine family, showcasing indigenous varieties alongside international grapes.", founded: 1995, owner: "Planeta Family", region: "Sicily", country: "Italy", lat: 37.5907, lng: 13.0050, grapeVarieties: ["Nero d'Avola", "Grillo", "Chardonnay"], wineStyles: ["red", "white"], featured: false, vineyardSize: "400 hectares", annualBottles: 2500000 },
  { name: "Tasca d'Almerita", slug: "tasca-dalmerita", description: "Historic Sicilian estate at Regaleali, pioneering quality winemaking on the island for nearly two centuries.", founded: 1830, owner: "Tasca Family", region: "Sicily", country: "Italy", lat: 37.7912, lng: 14.1039, grapeVarieties: ["Nero d'Avola", "Grillo", "Inzolia"], wineStyles: ["red", "white", "rosé"], featured: false, vineyardSize: "600 hectares", annualBottles: 3500000 },
];
