/**
 * New World — curated seed data.
 * Covers: USA (Napa Valley, Sonoma, Willamette Valley), Australia (Barossa Valley, Margaret River),
 *         New Zealand (Marlborough), South Africa (Stellenbosch), Argentina (Mendoza),
 *         Chile (Maipo Valley, Colchagua Valley)
 */

export const producers = [
  // USA — NAPA VALLEY
  {
    id: "prod-opus-one",
    name: "Opus One",
    country: "United States",
    region: "Napa Valley",
    website: "https://www.opusonewinery.com",
    foundedYear: 1979,
    description: "The Mondavi-Rothschild dream realized — Napa's most famous joint venture producing a single, iconic Bordeaux-style blend.",
  },
  // USA — SONOMA
  {
    id: "prod-kistler",
    name: "Kistler Vineyards",
    country: "United States",
    region: "Sonoma",
    website: "https://www.kistlervineyards.com",
    foundedYear: 1978,
    description: "California's most celebrated Chardonnay and Pinot Noir producer, crafting single-vineyard wines of Burgundian elegance and depth.",
  },
  // USA — WILLAMETTE VALLEY
  {
    id: "prod-domaine-drouhin-oregon",
    name: "Domaine Drouhin Oregon",
    country: "United States",
    region: "Willamette Valley",
    website: "https://www.domainedrouhin.com",
    foundedYear: 1987,
    description: "Burgundy's Drouhin family brought their expertise to Oregon, proving the Willamette Valley's potential for world-class Pinot Noir.",
  },
  // AUSTRALIA — BAROSSA VALLEY
  {
    id: "prod-penfolds",
    name: "Penfolds",
    country: "Australia",
    region: "Barossa Valley",
    website: "https://www.penfolds.com",
    foundedYear: 1844,
    description: "Australia's most famous winery and home of Grange — the southern hemisphere's most iconic and collectible wine.",
  },
  {
    id: "prod-henschke",
    name: "Henschke",
    country: "Australia",
    region: "Barossa Valley",
    website: "https://www.henschke.com.au",
    foundedYear: 1868,
    description: "Sixth-generation family winery producing Hill of Grace — Australia's rarest single-vineyard Shiraz from vines planted in the 1860s.",
  },
  // AUSTRALIA — MARGARET RIVER
  {
    id: "prod-leeuwin-estate",
    name: "Leeuwin Estate",
    country: "Australia",
    region: "Margaret River",
    website: "https://www.leeuwinestate.com.au",
    foundedYear: 1974,
    description: "Margaret River's founding estate, producing Australia's most acclaimed Chardonnay — the Art Series — alongside premium Cabernet.",
  },
  // NEW ZEALAND — MARLBOROUGH
  {
    id: "prod-cloudy-bay",
    name: "Cloudy Bay",
    country: "New Zealand",
    region: "Marlborough",
    website: "https://www.cloudybay.co.nz",
    foundedYear: 1985,
    description: "The wine that defined New Zealand Sauvignon Blanc for the world, establishing Marlborough as a global benchmark region.",
  },
  {
    id: "prod-felton-road",
    name: "Felton Road",
    country: "New Zealand",
    region: "Marlborough",
    website: "https://www.feltonroad.com",
    foundedYear: 1991,
    description: "Central Otago's finest producer, crafting biodynamic Pinot Noir and Chardonnay of stunning purity from Bannockburn's schist soils.",
  },
  // SOUTH AFRICA — STELLENBOSCH
  {
    id: "prod-kanonkop",
    name: "Kanonkop",
    country: "South Africa",
    region: "Stellenbosch",
    website: "https://www.kanonkop.co.za",
    foundedYear: 1910,
    description: "South Africa's most awarded estate and the benchmark for Pinotage, the country's signature grape variety, on the slopes of the Simonsberg.",
  },
  // ARGENTINA — MENDOZA
  {
    id: "prod-catena-zapata",
    name: "Catena Zapata",
    country: "Argentina",
    region: "Mendoza",
    website: "https://www.catenawines.com",
    foundedYear: 1902,
    description: "The family that proved high-altitude Argentine Malbec belongs among the world's greatest wines, pioneering viticulture above 1,000 meters.",
  },
  // CHILE — MAIPO VALLEY
  {
    id: "prod-concha-y-toro",
    name: "Concha y Toro",
    country: "Chile",
    region: "Maipo Valley",
    website: "https://www.conchaytoro.com",
    foundedYear: 1883,
    description: "Chile's largest and most historic winery, whose Don Melchor Cabernet Sauvignon stands among South America's greatest wines.",
  },
  // CHILE — COLCHAGUA VALLEY
  {
    id: "prod-montes",
    name: "Montes",
    country: "Chile",
    region: "Colchagua Valley",
    website: "https://www.monteswines.com",
    foundedYear: 1988,
    description: "Pioneering Chilean winery that proved Colchagua's hillside vineyards could produce world-class Syrah and Cabernet Sauvignon.",
  },
];

export const wines = [
  // NAPA VALLEY
  {
    id: "wine-opus-one-2019",
    name: "Opus One 2019",
    producer: "Opus One",
    producerId: "prod-opus-one",
    vintage: 2019,
    grapes: ["Cabernet Sauvignon", "Merlot", "Cabernet Franc", "Petit Verdot", "Malbec"],
    region: "Napa Valley",
    country: "United States",
    appellation: "Oakville AVA",
    type: "red",
    priceRange: "luxury",
    description: "Napa Valley's most famous Bordeaux-style blend, born from the partnership between Robert Mondavi and Baron Philippe de Rothschild.",
    tastingNotes: "Blackcurrant, dark plum, violet, graphite, and baking spice. Polished tannins with a rich, layered mid-palate and a long, elegant finish.",
    foodPairing: "Prime rib, grilled lamb chops with herb crust, aged Gouda, duck confit.",
  },
  // SONOMA
  {
    id: "wine-kistler-sonoma-mountain-chardonnay-2021",
    name: "Kistler Sonoma Mountain Chardonnay 2021",
    producer: "Kistler Vineyards",
    producerId: "prod-kistler",
    vintage: 2021,
    grapes: ["Chardonnay"],
    region: "Sonoma",
    country: "United States",
    appellation: "Sonoma Mountain AVA",
    type: "white",
    priceRange: "premium",
    description: "California's answer to great white Burgundy — single-vineyard Chardonnay of remarkable concentration and Burgundian finesse.",
    tastingNotes: "Ripe pear, Meyer lemon, hazelnut, brioche, and flint. Full-bodied with a creamy texture balanced by vibrant acidity and a long mineral finish.",
    foodPairing: "Roast chicken with tarragon, lobster with drawn butter, risotto with Parmigiano, halibut with beurre blanc.",
  },
  // WILLAMETTE VALLEY
  {
    id: "wine-domaine-drouhin-pinot-noir-2021",
    name: "Domaine Drouhin Oregon Pinot Noir 2021",
    producer: "Domaine Drouhin Oregon",
    producerId: "prod-domaine-drouhin-oregon",
    vintage: 2021,
    grapes: ["Pinot Noir"],
    region: "Willamette Valley",
    country: "United States",
    appellation: "Dundee Hills AVA",
    type: "red",
    priceRange: "premium",
    description: "A Burgundy family's expression of Oregon Pinot Noir, combining Old World elegance with New World fruit purity.",
    tastingNotes: "Fresh raspberry, cherry blossom, earthy spice, and a hint of forest floor. Silky tannins with bright acidity and a lingering, perfumed finish.",
    foodPairing: "Roasted salmon, duck breast with cherry sauce, grilled portobello mushrooms, Gruyère cheese.",
  },
  // BAROSSA VALLEY
  {
    id: "wine-penfolds-grange-2018",
    name: "Penfolds Grange 2018",
    producer: "Penfolds",
    producerId: "prod-penfolds",
    vintage: 2018,
    grapes: ["Shiraz", "Cabernet Sauvignon"],
    region: "Barossa Valley",
    country: "Australia",
    appellation: "Multi-regional",
    type: "red",
    priceRange: "luxury",
    description: "Australia's most iconic and collectible wine, multi-regional Shiraz aged in new American oak — a symbol of Australian winemaking ambition.",
    tastingNotes: "Dark chocolate, blackberry, sweet spice, espresso, and charred oak. Massive yet seamless, with velvety tannins and extraordinary depth.",
    foodPairing: "Slow-smoked brisket, kangaroo loin with native pepper, aged cheddar, dark chocolate fondant.",
  },
  {
    id: "wine-henschke-hill-of-grace-2017",
    name: "Henschke Hill of Grace 2017",
    producer: "Henschke",
    producerId: "prod-henschke",
    vintage: 2017,
    grapes: ["Shiraz"],
    region: "Barossa Valley",
    country: "Australia",
    appellation: "Eden Valley",
    type: "red",
    priceRange: "luxury",
    description: "Australia's rarest single-vineyard Shiraz, from pre-phylloxera vines planted in the 1860s in the Eden Valley — a national treasure.",
    tastingNotes: "Mulberry, dark plum, black pepper, sage, eucalyptus, and graphite. Profound concentration with fine tannins and a saline mineral finish.",
    foodPairing: "Grilled lamb with rosemary, aged rib-eye steak, kangaroo fillet, mature Comté cheese.",
  },
  // MARGARET RIVER
  {
    id: "wine-leeuwin-art-series-chardonnay-2020",
    name: "Leeuwin Estate Art Series Chardonnay 2020",
    producer: "Leeuwin Estate",
    producerId: "prod-leeuwin-estate",
    vintage: 2020,
    grapes: ["Chardonnay"],
    region: "Margaret River",
    country: "Australia",
    appellation: "Margaret River",
    type: "white",
    priceRange: "premium",
    description: "Australia's most celebrated Chardonnay, named for the commissioned artworks on each vintage label, barrel-fermented with incredible finesse.",
    tastingNotes: "Nectarine, grapefruit, cashew, struck flint, and toasted brioche. Complex and layered with a creamy palate and a taut, persistent finish.",
    foodPairing: "Western Australian marron, roast chicken, lobster thermidor, triple-cream Brie.",
  },
  // MARLBOROUGH
  {
    id: "wine-cloudy-bay-sauvignon-blanc-2023",
    name: "Cloudy Bay Sauvignon Blanc 2023",
    producer: "Cloudy Bay",
    producerId: "prod-cloudy-bay",
    vintage: 2023,
    grapes: ["Sauvignon Blanc"],
    region: "Marlborough",
    country: "New Zealand",
    appellation: "Marlborough",
    type: "white",
    priceRange: "mid",
    description: "The wine that put New Zealand on the world wine map — vibrant, aromatic Sauvignon Blanc that became a global phenomenon.",
    tastingNotes: "Passionfruit, lime, fresh-cut grass, gooseberry, and a flinty mineral edge. Crisp and refreshing with zesty acidity and a clean finish.",
    foodPairing: "Green-lipped mussels, goat cheese salad, Thai green curry, grilled asparagus, sushi.",
  },
  {
    id: "wine-felton-road-bannockburn-pinot-noir-2021",
    name: "Felton Road Bannockburn Pinot Noir 2021",
    producer: "Felton Road",
    producerId: "prod-felton-road",
    vintage: 2021,
    grapes: ["Pinot Noir"],
    region: "Marlborough",
    country: "New Zealand",
    appellation: "Central Otago",
    type: "red",
    priceRange: "premium",
    description: "Central Otago's finest Pinot Noir from biodynamic schist soils in Bannockburn — pure, perfumed, and hauntingly beautiful.",
    tastingNotes: "Wild cherry, thyme, dried rose petal, earthy minerality, and a hint of smoke. Silky texture with bright acidity and a long, graceful finish.",
    foodPairing: "Roasted duck breast, venison with berry compote, wild mushroom ragout, aged Gruyère.",
  },
  // STELLENBOSCH
  {
    id: "wine-kanonkop-pinotage-2020",
    name: "Kanonkop Pinotage 2020",
    producer: "Kanonkop",
    producerId: "prod-kanonkop",
    vintage: 2020,
    grapes: ["Pinotage"],
    region: "Stellenbosch",
    country: "South Africa",
    appellation: "Stellenbosch WO",
    type: "red",
    priceRange: "mid",
    description: "The definitive Pinotage — South Africa's signature grape at its most serious and ageworthy, from bush vines on the Simonsberg slopes.",
    tastingNotes: "Mulberry, plum, dark chocolate, coffee bean, and smoky spice. Full-bodied with firm, ripe tannins and a long, warming finish.",
    foodPairing: "Braai-grilled boerewors, bobotie, springbok loin, mature cheddar, sticky toffee pudding.",
  },
  // MENDOZA
  {
    id: "wine-catena-zapata-malbec-argentino-2020",
    name: "Catena Zapata Malbec Argentino 2020",
    producer: "Catena Zapata",
    producerId: "prod-catena-zapata",
    vintage: 2020,
    grapes: ["Malbec"],
    region: "Mendoza",
    country: "Argentina",
    appellation: "Mendoza",
    type: "red",
    priceRange: "premium",
    description: "High-altitude Malbec from vineyards above 1,000 meters in the Andes foothills, showcasing the grape's Argentine identity at its finest.",
    tastingNotes: "Ripe blackberry, violet, dark chocolate, crushed rock, and sweet spice. Velvety texture with polished tannins and a lifted, floral finish.",
    foodPairing: "Grilled Argentine asado, empanadas, chimichurri steak, provoleta cheese, dulce de leche desserts.",
  },
  // MAIPO VALLEY
  {
    id: "wine-don-melchor-2019",
    name: "Don Melchor Cabernet Sauvignon 2019",
    producer: "Concha y Toro",
    producerId: "prod-concha-y-toro",
    vintage: 2019,
    grapes: ["Cabernet Sauvignon"],
    region: "Maipo Valley",
    country: "Chile",
    appellation: "Puente Alto DO",
    type: "red",
    priceRange: "premium",
    description: "Chile's most famous icon wine from the Puente Alto vineyard in the upper Maipo Valley, rivaling top Bordeaux in blind tastings.",
    tastingNotes: "Blackcurrant, eucalyptus, cedar, dark chocolate, and graphite. Structured with firm, fine tannins and a long, mineral-driven finish.",
    foodPairing: "Grilled lamb rack, beef empanadas, pastel de choclo, aged Manchego cheese.",
  },
  // COLCHAGUA VALLEY
  {
    id: "wine-montes-alpha-m-2019",
    name: "Montes Alpha M 2019",
    producer: "Montes",
    producerId: "prod-montes",
    vintage: 2019,
    grapes: ["Cabernet Sauvignon", "Cabernet Franc", "Merlot", "Petit Verdot"],
    region: "Colchagua Valley",
    country: "Chile",
    appellation: "Apalta DO",
    type: "red",
    priceRange: "premium",
    description: "The flagship Bordeaux blend from Apalta's steep hillside vineyards, Chile's answer to a first-growth Bordeaux.",
    tastingNotes: "Cassis, blackberry, cigar box, dark chocolate, and Mediterranean herbs. Full-bodied with polished tannins and a long, complex finish.",
    foodPairing: "Grilled rib-eye with chimichurri, slow-braised short ribs, empanadas de pino, aged Gouda.",
  },
];

export const wineries = [
  // NAPA VALLEY
  { name: "Opus One", slug: "opus-one", description: "The Mondavi-Rothschild dream, Napa's most famous joint venture.", founded: 1979, owner: "Constellation & Rothschild", region: "Napa Valley", country: "United States", lat: 38.428, lng: -122.398, grapeVarieties: ["Cabernet Sauvignon", "Merlot", "Cabernet Franc"], wineStyles: ["red"], featured: true, vineyardSize: "67 hectares", annualBottles: 300000 },
  // SONOMA
  { name: "Kistler Vineyards", slug: "kistler-vineyards", description: "California's most celebrated Chardonnay and Pinot Noir producer.", founded: 1978, owner: "Steve Kistler", region: "Sonoma", country: "United States", lat: 38.3941, lng: -122.7233, grapeVarieties: ["Chardonnay", "Pinot Noir"], wineStyles: ["white", "red"], featured: true, vineyardSize: "50 hectares", annualBottles: 250000 },
  // WILLAMETTE VALLEY
  { name: "Domaine Drouhin Oregon", slug: "domaine-drouhin-oregon", description: "Burgundy's Drouhin family brought their expertise to Oregon, proving Willamette Valley's world-class potential.", founded: 1987, owner: "Drouhin Family", region: "Willamette Valley", country: "United States", lat: 45.2825, lng: -123.0556, grapeVarieties: ["Pinot Noir", "Chardonnay"], wineStyles: ["red", "white"], featured: true, vineyardSize: "55 hectares", annualBottles: 200000 },
  // BAROSSA VALLEY
  { name: "Penfolds", slug: "penfolds", description: "Australia's most famous winery, home of Grange.", founded: 1844, owner: "Treasury Wine Estates", region: "Barossa Valley", country: "Australia", lat: -34.477, lng: 138.996, grapeVarieties: ["Shiraz", "Cabernet Sauvignon"], wineStyles: ["red", "white"], featured: true, vineyardSize: "Multiple", annualBottles: 30000000 },
  { name: "Henschke", slug: "henschke", description: "Sixth-generation family winery producing Hill of Grace — Australia's rarest single-vineyard Shiraz.", founded: 1868, owner: "Henschke Family", region: "Barossa Valley", country: "Australia", lat: -34.6242, lng: 139.0553, grapeVarieties: ["Shiraz", "Cabernet Sauvignon", "Riesling"], wineStyles: ["red", "white"], featured: true, vineyardSize: "120 hectares", annualBottles: 350000 },
  // MARGARET RIVER
  { name: "Leeuwin Estate", slug: "leeuwin-estate", description: "Margaret River's founding estate, producing Australia's most acclaimed Chardonnay.", founded: 1974, owner: "Horgan Family", region: "Margaret River", country: "Australia", lat: -33.9362, lng: 115.0678, grapeVarieties: ["Chardonnay", "Cabernet Sauvignon", "Riesling"], wineStyles: ["white", "red"], featured: true, vineyardSize: "120 hectares", annualBottles: 600000 },
  // MARLBOROUGH
  { name: "Cloudy Bay", slug: "cloudy-bay", description: "The wine that defined New Zealand Sauvignon Blanc for the world.", founded: 1985, owner: "LVMH", region: "Marlborough", country: "New Zealand", lat: -41.479, lng: 173.835, grapeVarieties: ["Sauvignon Blanc", "Pinot Noir"], wineStyles: ["white", "red", "sparkling"], featured: true, vineyardSize: "240 hectares", annualBottles: 1500000 },
  { name: "Felton Road", slug: "felton-road", description: "Central Otago's finest producer, crafting biodynamic Pinot Noir of stunning purity.", founded: 1991, owner: "Nigel Greening", region: "Marlborough", country: "New Zealand", lat: -45.0310, lng: 169.1295, grapeVarieties: ["Pinot Noir", "Chardonnay", "Riesling"], wineStyles: ["red", "white"], featured: true, vineyardSize: "30 hectares", annualBottles: 120000 },
  // STELLENBOSCH
  { name: "Kanonkop", slug: "kanonkop", description: "South Africa's most awarded estate, benchmark for Pinotage.", founded: 1910, owner: "Krige Family", region: "Stellenbosch", country: "South Africa", lat: -33.878, lng: 18.910, grapeVarieties: ["Pinotage", "Cabernet Sauvignon"], wineStyles: ["red"], featured: false, vineyardSize: "100 hectares", annualBottles: 400000 },
  // MENDOZA
  { name: "Catena Zapata", slug: "catena-zapata", description: "The family that proved high-altitude Argentine Malbec belongs among the world's greatest wines.", founded: 1902, owner: "Catena Family", region: "Mendoza", country: "Argentina", lat: -33.4032, lng: -69.1429, grapeVarieties: ["Malbec", "Cabernet Sauvignon", "Chardonnay"], wineStyles: ["red", "white"], featured: true, vineyardSize: "700 hectares", annualBottles: 15000000 },
  // MAIPO VALLEY
  { name: "Concha y Toro", slug: "concha-y-toro", description: "Chile's largest and most historic winery, home of Don Melchor.", founded: 1883, owner: "Concha y Toro Group", region: "Maipo Valley", country: "Chile", lat: -33.6134, lng: -70.5675, grapeVarieties: ["Cabernet Sauvignon", "Carmenère", "Sauvignon Blanc"], wineStyles: ["red", "white"], featured: false, vineyardSize: "12000 hectares", annualBottles: 300000000 },
  // COLCHAGUA VALLEY
  { name: "Montes", slug: "montes", description: "Pioneering Chilean winery that proved Colchagua's hillside vineyards could produce world-class wines.", founded: 1988, owner: "Aurelio Montes", region: "Colchagua Valley", country: "Chile", lat: -34.5853, lng: -71.2126, grapeVarieties: ["Cabernet Sauvignon", "Syrah", "Malbec"], wineStyles: ["red"], featured: false, vineyardSize: "500 hectares", annualBottles: 10000000 },
];
